apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-upload-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-upload-api
  
  template:
    metadata:
      labels:
        app: resume-upload-api

    spec:
      containers:
       - name: resume-upload-api
         image: resume-upload-api:latest
         ports:
          - containerPort: 8080

         env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: hire-sense-secrets
                key: SUPABASE_URL

          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: hire-sense-secrets
                key: SUPABASE_KEY