apiVersion: v1
kind: Service
metadata:
  name: resume-upload-service

spec:
  type: NodePort
  selector:
    app: resume-upload-api

  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30080
     