apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: hire-sense-ingress

  annotations:
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   nginx.ingress.kubernetes.io/ssl-passthrough: "true"
   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
   nginx.ingress.kubernetes.io/proxy-body-size: "0"
   nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
   nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
   nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
   nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
   nginx.ingress.kubernetes.io/proxy-buffers: "4 128k"
   nginx.ingress.kubernetes.io/proxy-buffer-overflow-action: "drop"

spec:
 rules:
  - host: hire-sense.com
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: hire-sense-service
          port:
           number: 80
      
      - path: /api/backend-api
        pathType: Prefix
        backend:
         service:
          name: api-service
          port:
           number: 8000 
      
      - path: /api/resume-upload
        pathType: Prefix
        backend:
         service:
          name: resume-upload-service
          port:
           number: 8080
      
      - path: /api/job-posting
        pathType: Prefix
        backend:
         service:
          name: job-posting-service
          port: 
           number: 8000