apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-posting-deployment

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: job-posting-api
  
  template:
    metadata:
      labels:
        app: job-posting-api
    
    spec:
      containers:
       - name: job-posting-api
         image: job-posting-api:latest
         ports:
          - containerPort: 8000
         env: 
          - name: SUPBASE_URL
            valueFrom:
              secretKeyRef:
                name: hire-sense-secrets
                key: SUPABASE_URL
          
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: hire-sense-secrets
                key: SUPABASE_KEY
              