apiVersion: v1
kind: Secret

metadata:
  name: hire-sense-secrets

type: Opaque

data:
  GEMINI_API_KEY: QUl6YVN5QXQ2UXFjOVNtRTVfaXlzWDViaWttQXBIRUc3TkdpS3Zr
  SUPABASE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5SalpXbHhkR3B3ZUc5eFpXRjVhM0IwWkhKcUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTlRBMU5Ua3dNRFlzSW1WNGNDSTZNakEyTmpFek5UQXdObjAuN1VOUUNOdVBhZ1VHOFEwQ0o5VTB3b1VUYW1KdTNCM1B3TTJKRXVVQnBmRQ==
  SUPABASE_URL: aHR0cHM6Ly90Y2VpcXRqcHhvcWVheWtwdGRyai5zdXBhYmFzZS5jbw==
